### ISSUE TITLE
New ProductCard design

### ISSUE THREAD

**Issue by MiltonTulli** [mrdigre/SSR-ReactDemo#11]
Refactor product card style & add add-to-cart btn on each card

https://tailwindflex.com/isabella-kowalski/tailwind-products-list

<img width="542" alt="Screenshot 2023-08-15 at 13 45 13" src="https://github.com/mrdigre/SSR-ReactDemo/assets/25844967/2e994c52-1b85-4e95-ae54-36063bc505d0">

**Comment by mrdigre** [comment]
done
