### ISSUE TITLE
"Add to cart" button

### ISSUE THREAD

**Issue by MiltonTulli** [mrdigre/SSR-ReactDemo#14]
Make "add to cart" button prettier. Right now doesnt look good. 

https://tailwindcss.com/docs/border-radius#pill-buttons

**Comment by mrdigre** [comment]
Button has been modified:
![image](https://github.com/mrdigre/SSR-ReactDemo/assets/99774063/7ba9682a-2d85-4d67-9f4e-0f7a93786a6b)
